--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06.06.2019 21:23:27
-- Server version: 5.5.5-10.3.13-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO app.products(id, title, price, quantity, imei, mac, sn) VALUES
(1, 'Iphone 6', 300.00, 3, NULL, NULL, NULL),
(2, 'Зарядное устройство', 10.00, 10, NULL, NULL, NULL);