--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 02.06.2019 23:54:32
-- Server version: 5.5.5-10.3.13-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO app.category(id, name) VALUES
(1, 'Iphone'),
(2, 'Ipad'),
(3, 'MacBooks'),
(4, 'PC'),
(5, 'Аксессуары'),
(6, 'Meizu'),
(7, 'Huawei'),
(8, 'Распродажа');