--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 02.06.2019 23:54:35
-- Server version: 5.5.5-10.3.13-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO app.product(id, name, image, short_description, description, price, category_id) VALUES
(1, 'Товар', 'no-photo.jpg', 'Описание товара', 'Характеристики товара', 100, 8),
(5, 'Iphone 9', 'Screenshot_2019-02-14 iPhone – Сравнение моделей.png', 'Iphone', 'new', 100, 1),
(6, 'IPhone 6', 'Screenshot_2019-02-14 iPhone – Сравнение моделей.png', 'Золотой', 'Цвет: Iphone\r\nПамять: 64gb', 250, 1),
(7, 'Iphone X', 'Screenshot_2019-02-12 iPhone - Compare Models(21).png', 'Silver', 'Цвет: серебристый\r\nПамять: 128 gb', 500, 1),
(8, 'Iphone XS', 'Screenshot_2019-02-12 iPhone - Compare Models(27).png', 'Цвет: золотистый', 'Цвет: золотистый\r\nПамять: 256 gb', 1000, 1);